import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiOutlineDownload,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [showContact, setShowContact] = useState(false);
  const [showResume, setShowResume] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <button
                  onClick={() => setShowResume(true)}
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-4"
                >
                  Resume
                </button>
              </li>
              <li>
                <button
                  onClick={() => setShowContact(true)}
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-4"
                >
                  Contact
                </button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Adarsh Kumar
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Program Manager, Business Analyst & Graphics Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Professional logo designer and business analyst providing creative solutions and strategic insights. Let's collaborate to bring your vision to life!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              With extensive experience in semiconductor program management and business analytics, I've successfully delivered projects for
              <span className="text-teal-500"> Fortune 500 companies </span>
              and collaborated with <span className="text-teal-500">innovative startups </span>
              to drive technological advancement and business growth.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I explore my creative side through graphic design, crafting visually stunning solutions that bring ideas to life and enhance brand identity.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Program Management
              </h3>
              <p className="py-2">
                Leading semiconductor projects from conception to completion, ensuring timely delivery and quality standards.
              </p>
              <h4 className="py-4 text-teal-600">Expertise</h4>
              <p className="text-gray-800 py-1">Project Planning</p>
              <p className="text-gray-800 py-1">Risk Management</p>
              <p className="text-gray-800 py-1">Stakeholder Communication</p>
              <p className="text-gray-800 py-1">Resource Optimization</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Business Analysis
              </h3>
              <p className="py-2">
                Transforming complex data into actionable insights to drive business decisions and process improvements.
              </p>
              <h4 className="py-4 text-teal-600">Expertise</h4>
              <p className="text-gray-800 py-1">Data Analysis</p>
              <p className="text-gray-800 py-1">Process Optimization</p>
              <p className="text-gray-800 py-1">Requirements Gathering</p>
              <p className="text-gray-800 py-1">Business Process Modeling</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Graphic Design</h3>
              <p className="py-2">
                Creating visually compelling designs that effectively communicate your brand message and enhance user experience.
              </p>
              <h4 className="py-4 text-teal-600">Expertise</h4>
              <p className="text-gray-800 py-1">Brand Identity</p>
              <p className="text-gray-800 py-1">Logo Design</p>
              <p className="text-gray-800 py-1">Marketing Materials</p>
              <p className="text-gray-800 py-1">Visual Communication</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
        {showResume && (
          <div
            className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
            onClick={() => setShowResume(false)}
          >
            <div
              className="bg-white dark:bg-gray-800 p-8 rounded-lg max-w-4xl w-full mx-4 relative"
              onClick={(e) => e.stopPropagation()}
            >
              <button
                onClick={() => setShowResume(false)}
                className="absolute top-4 right-4 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
              >
                ✕
              </button>
              <h3 className="text-3xl py-1 dark:text-white mb-4">My Resume</h3>
              <div className="relative">
                <iframe
                  src="/Resume_AdarshKumar.pdf"
                  className="w-full h-[80vh] border-none"
                ></iframe>
                <a
                  href="/Resume_AdarshKumar.pdf"
                  download
                  className="absolute -top-14 right-4 bg-teal-500 text-white p-2 rounded-full hover:bg-teal-600 transition-colors duration-300"
                >
                  <AiOutlineDownload size={24} />
                </a>
              </div>
            </div>
          </div>
        )}
        {showContact && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white dark:bg-gray-800 p-8 rounded-lg max-w-xl w-full mx-4 relative">
              <button
                onClick={() => setShowContact(false)}
                className="absolute top-4 right-4 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
              >
                ✕
              </button>
              <h3 className="text-3xl py-1 dark:text-white mb-4">Contact Me</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 mb-6">
                Let's work together! Feel free to reach out for collaborations or just a friendly hello.
              </p>
              <form className="flex flex-col gap-4" action="https://formspree.io/f/xeogqbpr" method="POST">
                <div className="flex flex-col gap-2">
                  <label htmlFor="name" className="text-gray-800 dark:text-gray-200">Name</label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    className="p-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200 focus:outline-none focus:ring-2 focus:ring-teal-500"
                    placeholder="Your name"
                    required
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <label htmlFor="email" className="text-gray-800 dark:text-gray-200">Email</label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    className="p-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200 focus:outline-none focus:ring-2 focus:ring-teal-500"
                    placeholder="your@email.com"
                    required
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <label htmlFor="message" className="text-gray-800 dark:text-gray-200">Message</label>
                  <textarea
                    id="message"
                    name="message"
                    rows="4"
                    className="p-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200 focus:outline-none focus:ring-2 focus:ring-teal-500"
                    placeholder="Your message here..."
                    required
                  ></textarea>
                </div>
                <button
                  type="submit"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md hover:opacity-90 transition-opacity duration-300 mt-4"
                >
                  Send Message
                </button>
              </form>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}